# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb6f45b2bccf003b4592a81aa1505462f58d30db330ad00fc9275d38f517850fd19a088ecb8b7e81fcf2f5c86a198aeffdfa0aeeb670a89706bdfb2b036c6ee8

test:
  secret_key_base: 7dff1a0d093c40ce6d19239ff809e4a7df98de77758b46c2d29dc7e343567339d4f2b1581829b1372eb3aa81ab46528aa15ea65cf49c606da8a9123088d1c141

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
